[package]
name = "contract"
edition = "2024"         # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
deepbook = { git = "https://github.com/MystenLabs/deepbookv3", subdir = "packages/deepbook", rev = "4c87222f01d9dcc657f7fada45319f9ff1d5fe78" }
# Read more about the package management system options:
# https://docs.sui.io/guides/developer/sui-101/move-package-management
